### ISSUE TITLE
Tesseract giving series of errors

### ISSUE THREAD

**Issue by aryansaw03** [tesseract-ocr/tesseract#1565]
```
from PIL import Image
import pytesseract
tesseract_cmd = 'C:\\Program Files (x86)\\Tesseract-OCR\\tesseract'
im = Image.open("jumbled.jpg")
text = pytesseract.image_to_string(im, lang = 'eng')
print(text)
```

I am trying to use tesseract for character recognition on an image (attached below)
![jumbled](https://user-images.githubusercontent.com/37314626/39669602-c9955a02-50be-11e8-81ad-83c97c5cb82d.jpg)

but I am getting the following errors in command line, I am new to python and OCR, please help.

```
C:\Users\aryan\Documents\Computer\Programming\Atom Test>python HQSolver.py
Traceback (most recent call last):
  File "HQSolver.py", line 6, in <module>
    text = pytesseract.image_to_string(im, lang = 'eng')
  File "C:\Users\aryan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 193, in image_to_string
    return run_and_get_output(image, 'txt', lang, config, nice)
  File "C:\Users\aryan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 140, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\aryan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pytesseract\pytesseract.py", line 111, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Users\aryan\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\aryan\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I already tried to change the pytesseract.py from
`tesseract_cmd = 'tesseract'`
to
`tesseract_cmd = '/usr/local/bin/tesseract'`

**Comment by zdenop** [comment]
We do not provide support for 3rd party (python wrapper) project. Please contact its author or use tesseract user forum.

**Comment by ryanguera** [comment]
nic
