### ISSUE TITLE
Training From Scratch: "No X11 DISPLAY variable was set"

### ISSUE THREAD

**Issue by GDStephen** [tesseract-ocr/tesseract#1577]
### Environment

* **Tesseract Version**: 4.0.0-beta.1-65-gf8e2
* **Platform**: 16.04.1-Ubuntu

### Current Behavior:
Training From Scratch:
```
training/lstmtraining --debug_interval 100   
--traineddata ~/tesstutorial/engtrain/eng/eng.traineddata   
--net_spec '[1,36,0,1 Ct3,3,16 Mp3,3 Lfys48 Lfx96 Lrx96 Lfx256 O1c111]'   
--model_output ~/tesstutorial/engoutput/base 
--learning_rate 20e-4   
--train_listfile ~/tesstutorial/engtrain/eng.training_files.txt   
--eval_listfile ~/tesstutorial/engeval/eng.training_files.txt   
--max_iterations 20000
```

result:
```
Starting sh -c "trap 'kill %1' 0 1 2 ; java -Xms1024m -Xmx2048m -jar /root/tess/tesseract/java/ScrollView.jar & wait"
ScrollView: Waiting for server...
Socket started on port 8461
Created window Convolve of size 1557, 580
Client connected
Created window ConvNL of size 1020, 656
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at javax.swing.JFrame.<init>(JFrame.java:233)
	at com.google.scrollview.ui.SVWindow.<init>(SVWindow.java:204)
	at com.google.scrollview.ScrollView.processInput(ScrollView.java:340)
	at com.google.scrollview.ScrollView.IOLoop(ScrollView.java:120)
	at com.google.scrollview.ScrollView.main(ScrollView.java:398)
sh: 1: kill: No such process

Created window Lfys48 of size 530, 2000
```

### Expected Behavior:
Start Training.

**Comment by Shreeshrii** [comment]
Change debug_interval to 0 or -1 instead of 100.

Problem is related to running scrollview.jar

Changing debug level will not try to run it.

**Comment by GDStephen** [comment]
thks Shreeshrii:
Edit `./viewer/svutil.cpp` delete `java -Xms1024m -Xmx2048m -jar /root/tess/tesseract/java/ScrollView.jar &`.
It worked.
