### ISSUE TITLE
regression: lstmtraining crashing for plus-minus training

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#1602]
$ uname -a
Linux tesseract-ocr 4.4.0-122-generic #146-Ubuntu SMP Mon Apr 23 15:33:25 UTC 2018 ppc64le ppc64le ppc64le GNU/Linux

$ tesseract -v
tesseract 4.0.0-beta.1-270-g5a56
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0

```
Loaded 1/1 pages (1-1) of document ./san-plus_train/san.pothi-1-010008.exp0.lstmf
[New Thread 0x3fffb599f100 (LWP 26673)]
[Thread 0x3fffb519f100 (LWP 26672) exited]
Loaded 1/1 pages (1-1) of document ./san-plus_train/san.pothi-1-010009.exp0.lstmf
[Thread 0x3fffb599f100 (LWP 26673) exited]
[New Thread 0x3fffb599f100 (LWP 26674)]
[New Thread 0x3fffb519f100 (LWP 26675)]
[New Thread 0x3fffb6c5f100 (LWP 26676)]
Iteration 0: ALIGNED TRUTH : खखंखंख..ं. २ २   अअ अ...     ६०          पाननननन ११२६
Iteration 0: BEST OCR TEXT : । किच्ज        णवक्
File ./san-plus_train/san.pothi-1-010001.exp0.lstmf page 0 :
Mean rms=3.977%, delta=19.917%, train=128.571%(100%), skip ratio=0%
[New Thread 0x3fffb499f100 (LWP 26677)]
Loaded 1/1 pages (1-1) of document ./san-plus_train/san.pothi-1-01000a.exp0.lstmf
[Thread 0x3fffb499f100 (LWP 26677) exited]

Thread 1 "lstmtraining" received signal SIGSEGV, Segmentation fault.
0x00003fffb7b52fcc in tesseract::Tanh (x=nan(0x94789e0000000)) at functions.h:50
50        if (TanhTable[index] == 0.0 && index > 0) {
(gdb) backtrace
#0  0x00003fffb7b52fcc in tesseract::Tanh (x=nan(0x94789e0000000)) at functions.h:50
#1  tesseract::GFunc::operator() (this=<synthetic pointer>, x=nan(0x94789e0000000)) at functions.h:111
#2  tesseract::FuncInplace<tesseract::GFunc> (inout=<optimized out>, n=<optimized out>) at functions.h:149
#3  tesseract::FullyConnected::ForwardTimeStep (this=<optimized out>, t=<optimized out>, output_line=<optimized out>)
    at fullyconnected.cpp:187
#4  0x00003fffb7b53768 in tesseract::FullyConnected::ForwardTimeStep (this=0x102a57a0, d_input=<optimized out>, t=<optimized out>,
    output_line=0x1069d0b0) at fullyconnected.cpp:209
#5  0x00003fffb7b539e4 in tesseract::FullyConnected::Forward () at fullyconnected.cpp:151
#6  0x00003fffb703e8a4 in GOMP_parallel () from /usr/lib/powerpc64le-linux-gnu/libgomp.so.1
#7  0x00003fffb7b550e4 in tesseract::FullyConnected::Forward (this=0x102a57a0, debug=<optimized out>, input=...,
    input_transpose=<optimized out>, scratch=0x3fffffffe770, output=0x10b72760) at fullyconnected.cpp:137
#8  0x00003fffb7b8f538 in tesseract::Series::Forward (this=0x102a5320, debug=<optimized out>, input=...,
    input_transpose=<optimized out>, scratch=0x3fffffffe770, output=0x10b72760) at series.cpp:120
#9  0x00003fffb7b8f538 in tesseract::Series::Forward (this=0x102a5200, debug=<optimized out>, input=...,
    input_transpose=<optimized out>, scratch=0x3fffffffe770, output=0x3fffffffdd88) at series.cpp:120
#10 0x00003fffb7b662f8 in tesseract::LSTMRecognizer::RecognizeLine (this=0x3fffffffe430, image_data=..., invert=<optimized out>,
    debug=<optimized out>, re_invert=<optimized out>, upside_down=<optimized out>, scale_factor=0x3fffffffdbbc,
    inputs=0x3fffffffdc58, outputs=0x3fffffffdd88) at lstmrecognizer.cpp:256
#11 0x00003fffb7b6e238 in tesseract::LSTMTrainer::PrepareForBackward (this=0x3fffffffe428, trainingdata=0x3fffa8000910,
    fwd_outputs=0x3fffffffdd88, targets=0x3fffffffde18) at lstmtrainer.cpp:874
#12 0x00003fffb7b6e8d0 in tesseract::LSTMTrainer::TrainOnLine (this=<optimized out>, trainingdata=<optimized out>,
    batch=<optimized out>) at lstmtrainer.cpp:799
#13 0x0000000010006674 in tesseract::LSTMTrainer::TrainOnLine (batch=false, samples_trainer=<optimized out>, this=<optimized out>)
    at ../../src/lstm/lstmtrainer.h:264
#14 main (argc=1, argv=0x3ffffffff3c8) at lstmtraining.cpp:201
(gdb) quit
```

**Comment by Shreeshrii** [comment]
Ran into same issue again. It seems related to using plus-minus type of training.

```
Starting program: /usr/local/bin/lstmtraining --continue_from ../tessdata_best/san-iast.lstm --old_traineddata ../tessdata_best/san-iast.traineddata --traineddata ./san-trained-from-san-iast/san/san.traineddata --max_iterations 200 --debug_interval -1 --train_listfile ./san-train/san.training_files.txt --model_output ./san-trained-from-san-iast/plus
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/powerpc64le-linux-gnu/libthread_db.so.1".
Loaded file ../tessdata_best/san-iast.lstm, unpacking...
Warning: LSTMTrainer deserialized an LSTMRecognizer!
Code range changed from 325 to 327!
Num (Extended) outputs,weights in Series:
  1,48,0,1:1, 0
Num (Extended) outputs,weights in Series:
  C3,3:9, 0
  Ft16:16, 160
Total weights = 160
  [C3,3Ft16]:16, 160
  Mp3,3:16, 0
  Lfys64:64, 20736
  Lfx64:64, 33024
  Lrx64:64, 33024
  Lfx192:192, 197376
  Fc327:327, 63111
Total weights = 347431
Previous null char=2 mapped to 2
Continuing from ../tessdata_best/san-iast.lstm
[New Thread 0x3fffb6c5f100 (LWP 23145)]
Loaded 1619/1619 pages (1-1619) of document ./san-train/san.2.FreeSans.exp0.lstmf
[Thread 0x3fffb6c5f100 (LWP 23145) exited]
[New Thread 0x3fffb6c5f100 (LWP 23146)]
[New Thread 0x3fffb645f100 (LWP 23147)]
[New Thread 0x3fffb5c5f100 (LWP 23148)]
[New Thread 0x3fffb545f100 (LWP 23149)]
[New Thread 0x3fffb354f100 (LWP 23150)]
[New Thread 0x3fffb2d4f100 (LWP 23151)]
[New Thread 0x3fffb254f100 (LWP 23152)]
[New Thread 0x3fffb1d4f100 (LWP 23153)]
Loaded 1649/1649 pages (1-1649) of document ./san-train/san.0.Arial_Unicode_MS.exp0.lstmf
[Thread 0x3fffb6c5f100 (LWP 23146) exited]
Loaded 1602/1602 pages (1-1602) of document ./san-train/san.1.Siddhanta.exp0.lstmf
Loaded 1619/1619 pages (1-1619) of document ./san-train/san.2.Adobe_Devanagari.exp0.lstmf
[Thread 0x3fffb5c5f100 (LWP 23148) exited]
[Thread 0x3fffb645f100 (LWP 23147) exited]
Loaded 1655/1655 pages (1-1655) of document ./san-train/san.0.Noto_Sans.exp0.lstmf
[Thread 0x3fffb354f100 (LWP 23150) exited]
Loaded 1602/1602 pages (1-1602) of document ./san-train/san.1.Siddhanta-Calcutta.exp0.lstmf
[Thread 0x3fffb2d4f100 (LWP 23151) exited]
Loaded 1655/1655 pages (1-1655) of document ./san-train/san.0.Chandas.exp0.lstmf
[Thread 0x3fffb545f100 (LWP 23149) exited]
Loaded 1656/1656 pages (1-1656) of document ./san-train/san.0.Adobe_Devanagari.exp0.lstmf
Loaded 1600/1600 pages (1-1600) of document ./san-train/san.1.Sahadeva.exp0.lstmf
[Thread 0x3fffb254f100 (LWP 23152) exited]
[Thread 0x3fffb1d4f100 (LWP 23153) exited]
[New Thread 0x3fffb1d4f100 (LWP 23154)]
[New Thread 0x3fffb254f100 (LWP 23155)]
[New Thread 0x3fffb545f100 (LWP 23156)]
Iteration 0: ALIGNED TRUTH : हरीं क्लीं ऐं क्लूं स्त्रीं गलयौं द्रांद्रीं क्लीं क्लूं सः,
Iteration 0: BEST OCR TEXT : हीं क्लीं ऐं क्लूं स्त्री गलयौं द्रांद्री क्ली क्लूं सः,
File /tmp/tmp.GjTunwc3Ra/san/san.2.FreeSans.exp0.lstmf page 538 :
Mean rms=1.044%, delta=4.545%, train=9.677%(45.455%), skip ratio=0%
[New Thread 0x3fffb2d4f100 (LWP 23157)]
Loaded 1651/1651 pages (1-1651) of document ./san-train/san.0.Nakula.exp0.lstmf
[Thread 0x3fffb2d4f100 (LWP 23157) exited]

Thread 1 "lstmtraining" received signal SIGSEGV, Segmentation fault.
0x00003fffb7b5a8d8 in tesseract::Logistic (x=nan(0x8000000000000)) at functions.h:68
68        if (LogisticTable[index] == 0.0) {
(gdb) backtrace
#0  0x00003fffb7b5a8d8 in tesseract::Logistic (x=nan(0x8000000000000)) at functions.h:68
#1  tesseract::FFunc::operator() (this=<synthetic pointer>, x=nan(0x8000000000000)) at functions.h:84
#2  tesseract::FuncInplace<tesseract::FFunc> (inout=<optimized out>, n=<optimized out>) at functions.h:149
#3  tesseract::LSTM::Forward () at lstm.cpp:364
#4  0x00003fffb703efe8 in GOMP_parallel_sections () from /usr/lib/powerpc64le-linux-gnu/libgomp.so.1
#5  0x00003fffb7b60020 in tesseract::LSTM::Forward (this=0x1028bf70, debug=<optimized out>, input=..., input_transpose=<optimized out>, scratch=0x3fffffffe730, output=0x107f1190) at lstm.cpp:322
#6  0x00003fffb7b8e488 in tesseract::Series::Forward (this=0x10289ef0, debug=<optimized out>, input=..., input_transpose=<optimized out>, scratch=0x3fffffffe730, output=0x3fffffffdd48)
    at series.cpp:123
#7  0x00003fffb7b65278 in tesseract::LSTMRecognizer::RecognizeLine (this=0x3fffffffe3f0, image_data=..., invert=<optimized out>, debug=<optimized out>, re_invert=<optimized out>,
    upside_down=<optimized out>, scale_factor=0x3fffffffdb7c, inputs=0x3fffffffdc18, outputs=0x3fffffffdd48) at lstmrecognizer.cpp:256
#8  0x00003fffb7b6d1b8 in tesseract::LSTMTrainer::PrepareForBackward (this=0x3fffffffe3e8, trainingdata=0x3fffac001b50, fwd_outputs=0x3fffffffdd48, targets=0x3fffffffddd8) at lstmtrainer.cpp:874
#9  0x00003fffb7b6d850 in tesseract::LSTMTrainer::TrainOnLine (this=<optimized out>, trainingdata=<optimized out>, batch=<optimized out>) at lstmtrainer.cpp:799
#10 0x00000000100065d4 in tesseract::LSTMTrainer::TrainOnLine (batch=false, samples_trainer=<optimized out>, this=<optimized out>) at ../../src/lstm/lstmtrainer.h:264
#11 main (argc=1, argv=0x3ffffffff388) at lstmtraining.cpp:201
(gdb)
```

**Comment by Shreeshrii** [comment]
I built  tesseract for a commit from one month back and the plus training is working fine.

```
 tesseract -v
tesseract 4.0.0-beta.1-233-g6c08e
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0
```
```
Loaded file ../tessdata_best/script/Devanagari.lstm, unpacking...
Warning: LSTMTrainer deserialized an LSTMRecognizer!
Code range changed from 217 to 345!
Num (Extended) outputs,weights in Series:
  1,48,0,1:1, 0
Num (Extended) outputs,weights in Series:
  C3,3:9, 0
  Ft16:16, 160
Total weights = 160
  [C3,3Ft16]:16, 160
  Mp3,3:16, 0
  Lfys64:64, 20736
  Lfx64:64, 33024
  Lrx64:64, 33024
  Lfx512:512, 1181696
  Fc345:345, 176985
Total weights = 1445625
Previous null char=2 mapped to 2
Continuing from ../tessdata_best/script/Devanagari.lstm
Loaded 2584/2584 pages (1-2584) of document ./san-eval/san.Murty_Sanskrit.exp0.lstmf
Loaded 1654/1654 pages (1-1654) of document ./san-train/san.0.Sarala_Bold.exp0.lstmf
Loaded 1632/1632 pages (1-1632) of document ./san-train-iast/san.0.Amiko_Semi-Bold.exp0.lstmf
Loaded 1639/1639 pages (1-1639) of document ./san-train/san.1.Khula_Light.exp0.lstmf
Loaded 1653/1653 pages (1-1653) of document ./san-train/san.0.Aparajita_Bold_Italic.exp0.lstmf
Loaded 1650/1650 pages (1-1650) of document ./san-train/san.0.Teko_Light.exp0.lstmf
Loaded 1638/1638 pages (1-1638) of document ./san-train/san.1.Khula_Semi-Bold.exp0.lstmf
Loaded 1652/1652 pages (1-1652) of document ./san-train/san.0.Khula_Ultra-Bold.exp0.lstmf
Loaded 1650/1650 pages (1-1650) of document ./san-train/san.0.Tillana_Medium.exp0.lstmf
Iteration 0: ALIGNED TRUTH : परतस्त्रिषु उत्पन्नो शक्तिभिः नयिष्ये प्रव्रज उत्पद्यंते निरुच्यंते सराः
Iteration 0: BEST OCR TEXT : परतस्लिषु उत्पन्नो शक्तिभिः नयिष्ये प्रव्रज उत्पद्यंते निरुच्यंते सराः
File /tmp/tmp.AdwSQFkg2D/san/san.Murty_Sanskrit.exp0.lstmf page 857 :
Mean rms=0.709%, delta=2.49%, train=5.556%(12.5%), skip ratio=0%
Loaded 1656/1656 pages (1-1656) of document ./san-train/san.0.Martel_Ultra-Light.exp0.lstmf
Iteration 1: ALIGNED TRUTH : दैवे युगसहस्रे द्े ब्राह्मः कल्पौ तु तौ नृणाम् जप्त्वा अदंष््रा महाविष्णुं पञ्चवट्यां
Iteration 1: BEST OCR TEXT : दैवे युगसहस्े े ब्राह्मः कल्पौ तु तौ नृणाम्‌ जप्त्वा अदंष्ट्वा महाविष्णुं पञ्चवट्यां
File /tmp/tmp.PT9GcxsWiR/san/san.0.Sarala_Bold.exp0.lstmf page 494 :
Mean rms=0.779%, delta=2.253%, train=6.226%(22.917%), skip ratio=0%
Loaded 1654/1654 pages (1-1654) of document ./san-train/san.0.YashomudraLight_Italic.exp0.lstmf
Iteration 2: ALIGNED TRUTH : गत्वा तु मण्डलम् स्म वै य अपि मया तु वैष्णवं सर्वमायुरेति ज्योग्जीवति स्वस्थानं
Iteration 2: BEST OCR TEXT : गत्वा तु म्रण्डलम्‌ स्म वै य अपि मया तु वैष्णवं सर्वमरायुरेति ज्योग्जीवति स्वस्थानं
File /tmp/tmp.PT9GcxsWiR/san/san.0.Aparajita_Bold_Italic.exp0.lstmf page 571 :
Mean rms=0.839%, delta=2.795%, train=5.417%(20.406%), skip ratio=0%
```

I will try to see if I can find out which commit caused the problem.

**Comment by amitdo** [comment]
>I will try to see if I can find out which commit caused the problem.

Please do...

**Comment by Shreeshrii** [comment]
@amitdo  Not able to isolate the problem yet. It works fine in most cases.

**Comment by Shreeshrii** [comment]
Also see https://github.com/tesseract-ocr/tesseract/issues/1798

Closing issue.
