### ISSUE TITLE
multi language pdf reading error with latest jar file

### ISSUE THREAD

**Issue by Mad-u1** [tesseract-ocr/tesseract#1617]
hi all,
Could you please look into this, when I'm trying to access with latest jar file (4.0.2). I'm getting the following error. i.e.

contains_unichar_id(unichar_id):Error:Assert failed:in file c:\projects\github\tesseract-ocr\src\ccutil\unicharset.h, line 511
Exception in thread "main" java.lang.Error: Invalid memory access
	at com.sun.jna.Native.invokePointer(Native Method)
	at com.sun.jna.Function.invokePointer(Function.java:470)
	at com.sun.jna.Function.invoke(Function.java:404)
	at com.sun.jna.Function.invoke(Function.java:315)
	at com.sun.jna.Library$Handler.invoke(Library.java:212)
	at com.sun.proxy.$Proxy1.TessBaseAPIGetUTF8Text(Unknown Source)
	at net.sourceforge.tess4j.Tesseract.getOCRText(Tesseract.java:433)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:288)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:209)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:193)
	at com.test.TestX1.main(TestX1.java:20)

**Comment by zdenop** [comment]
Please respect guidelines for issues posting: We do not provide support for 3rd party project.
