### ISSUE TITLE
Teseract language error

### ISSUE THREAD

**Issue by al-lan-mandragoran** [tesseract-ocr/tesseract#2237]
* **Tesseract Version**: 3.05.02

* **Platform**: Windows 64 Bit
I am trying to run tesseract and it is giving me this language error.  I am not quite sure what to do.

Error Code:
Traceback (most recent call last):
  File "C:\Users\aiden\Desktop\Python\IR\IR Test 6.py", line 6, in <module>
    print (pytesseract.image_to_string(Image.open('test.png')))
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pytesseract\pytesseract.py", line 309, in image_to_string
    }[output_type]()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pytesseract\pytesseract.py", line 308, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pytesseract\pytesseract.py", line 218, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\pytesseract\pytesseract.py", line 194, in run_tesseract
    raise TesseractError(status_code, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, 'Error opening data file \\Program Files\\Tesseract\\tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory. Failed loading language \'eng\' Tesseract couldn\'t load any languages! Could not initialize tesseract.')

My Code:

from PIL import Image
#import image
import pytesseract
import PIL
pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract\tesseract.exe"
print (pytesseract.image_to_string(Image.open('test.png')))
print (pytesseract.image_to_string(Image.open('test-english.jpg'), lang='eng'))

Any and all help would be appreciated

**Comment by zdenop** [comment]
We do not support 3rd party project.
Please post your issue on tesseract user forum or directly at pytesseract project
