### ISSUE TITLE
Issue 13592: tesseract-ocr/fuzzer-api: Ill in ERRCODE::error

### ISSUE THREAD

**Issue by stweil** [tesseract-ocr/tesseract#2301]
OSS Fuzz triggers an assertion in Tesseract:

    contains_unichar_id(unichar_id):Error:Assert failed:in file ../../src/ccutil/unicharset.h, line 502
     #0 0x85e15d in ERRCODE::error(char const*, TessErrorLogCode, char const*, ...) const tesseract/src/ccutil/errcode.cpp:84:7
     #1 0x57b8b4 in UNICHARSET::get_isupper(int) const tesseract/src/ccutil/unicharset.h:502:5
     #2 0x90e412 in tesseract::Dict::case_ok(WERD_CHOICE const&, UNICHARSET const&) const tesseract/src/dict/context.cpp:51:20
     #3 0x76661e in tesseract::Dict::AcceptableResult(WERD_RES*) const tesseract/src/dict/stopper.cpp:118:7

**Comment by stweil** [comment]
This issue was fixed with pull request #2306.
