### ISSUE TITLE
how to change min characters value

### ISSUE THREAD

**Issue by suravijayjilla** [tesseract-ocr/tesseract#2805]
Hi,

I am using ubuntu 16.04 LTS, python 3.6.9, tesseract 4.1.1,
If I try to find and rotate an image using tesseract it gives the below error, 

Traceback (most recent call last):
  File "/home/bharath/Downloads/image_rotator/test.py", line 6, in <module>
    print(pytesseract.image_to_osd(Image.open(file_name)))
  File "/home/bharath/text/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 442, in image_to_osd
    }[output_type]()
  File "/home/bharath/text/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 441, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/bharath/text/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 253, in run_and_get_output
    run_tesseract(**kwargs)
  File "/home/bharath/text/lib/python3.6/site-packages/pytesseract/pytesseract.py", line 229, in run_tesseract
    raise TesseractError(proc.returncode, get_errors(error_string))
pytesseract.pytesseract.TesseractError: (1, 'Tesseract Open Source OCR Engine v4.1.1-rc2-17-g6343 with Leptonica Warning: Invalid resolution 0 dpi. Using 70 instead. Estimating resolution as 119 Warning. Invalid resolution 0 dpi. Using 70 instead. Too few characters. Skipping this page Error during processing.')

Searching google for this issue, one says to change this value min_characters_to_try	50 and check but I am unable to change that value.
Please help me on this issue.

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: use tesseract user forum for asking questions/support.
