### ISSUE TITLE
LeakSanitizer: detected memory leaks running stringrenderer_test on AArch64

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#3157]
```
Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-124-generic aarch64)
```

Tesseract built using
```
# for googletest and test submodules
git submodule update --init --recursive

# fonts needed for stringrenderer and ligature-table tests
cp ~/testing/*.* ~/tesseract/test/testing/

./autogen.sh
mkdir -p bin/unittest
cd bin/unittest
../../configure --enable-openmp --disable-graphics --disable-shared --with-tensorflow=no --disable-debug  --disable-opencl 'CXXFLAGS=-g -O2 -Wall -Wextra -Wpedantic -fsanitize=address,undefined -fstack-protector-strong -ftrapv'
make  -j 4
sudo make install
sudo ldconfig
make training -j 4
sudo make training-install
# Run the unit tests:
make check
cd ../..
```

```
tesseract -v
tesseract 5.0.0-alpha-822-gdea0
 leptonica-1.75.3
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0

 Found NEON
 Found OpenMP 201511
```

**Comment by Shreeshrii** [comment]
```

[----------] Global test environment tear-down
[==========] 24 tests from 3 test suites ran. (670 ms total)
[  PASSED  ] 24 tests.

  YOU HAVE 1 DISABLED TEST


=================================================================
==13420==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 5376 byte(s) in 7 object(s) allocated from:
    #0 0xffff857fdeeb in __interceptor_realloc (/usr/lib/aarch64-linux-gnu/libasan.so.4+0xcfeeb)
    #1 0xffff84fef6a3  (/usr/lib/aarch64-linux-gnu/libfontconfig.so.1+0x1e6a3)
    #2 0xffff84fefdaf  (/usr/lib/aarch64-linux-gnu/libfontconfig.so.1+0x1edaf)
    #3 0xffff84fec80f in FcFontRenderPrepare (/usr/lib/aarch64-linux-gnu/libfontconfig.so.1+0x1b80f)
    #4 0xffff84feccff in FcFontMatch (/usr/lib/aarch64-linux-gnu/libfontconfig.so.1+0x1bcff)
    #5 0xffff84f9ccff  (/usr/lib/aarch64-linux-gnu/libpangoft2-1.0.so.0+0xacff)
    #6 0xffff84f9cfb7  (/usr/lib/aarch64-linux-gnu/libpangoft2-1.0.so.0+0xafb7)
    #7 0xffff84f9b40f  (/usr/lib/aarch64-linux-gnu/libpangoft2-1.0.so.0+0x940f)
    #8 0xaaaad8208d3b in tesseract::FontUtils::IsAvailableFont(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) ../../../../src/training/pango_font_info.cpp:509
    #9 0xaaaad820f94f in tesseract::FontUtils::IsAvailableFont(char const*) ../../../../src/training/pango_font_info.h:151
    #10 0xaaaad820f94f in tesseract::FontUtils::ListAvailableFonts[abi:cxx11]() ../../../../src/training/pango_font_info.cpp:597
    #11 0xaaaad821700b in tesseract::FontUtils::SelectFont(char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*) ../../../../src/training/pango_font_info.cpp:729
    #12 0xaaaad825833b in tesseract::StringRenderer::RenderAllFontsToImage(double, char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, Pix**) ../../../../src/training/stringrenderer.cpp:841
    #13 0xaaaad818273b in TestBody ../../../unittest/stringrenderer_test.cc:421
    #14 0xaaaad848f7fb in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ../../../googletest/googletest/src/gtest.cc:2433
    #15 0xaaaad848f7fb in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ../../../googletest/googletest/src/gtest.cc:2469
    #16 0xaaaad841c7cf in testing::Test::Run() ../../../googletest/googletest/src/gtest.cc:2508
    #17 0xaaaad841d5b7 in testing::Test::Run() ../../../googletest/googletest/src/gtest.cc:2499
    #18 0xaaaad841d5b7 in testing::TestInfo::Run() ../../../googletest/googletest/src/gtest.cc:2684
    #19 0xaaaad841e83b in testing::TestSuite::Run() ../../../googletest/googletest/src/gtest.cc:2816
    #20 0xaaaad8422097 in testing::internal::UnitTestImpl::RunAllTests() ../../../googletest/googletest/src/gtest.cc:5338
    #21 0xaaaad84914ff in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ../../../googletest/googletest/src/gtest.cc:2433
    #22 0xaaaad84914ff in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ../../../googletest/googletest/src/gtest.cc:2469
    #23 0xaaaad84247f3 in testing::UnitTest::Run() ../../../googletest/googletest/src/gtest.cc:4925
    #24 0xaaaad816bc83 in RUN_ALL_TESTS() ../../../googletest/googletest/include/gtest/gtest.h:2473
    #25 0xaaaad816bc83 in main ../../../unittest/../googletest/googletest/src/gtest_main.cc:45
    #26 0xffff83e7471f in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x2071f)
    #27 0xaaaad816c32f  (/home/ubuntu/tesseract/bin/unittest/unittest/stringrenderer_test+0x70632f)


...
etc
```

Complete log attached

[stringrenderer_test.log.txt](https://github.com/tesseract-ocr/tesseract/files/5581134/stringrenderer_test.log.txt)

**Comment by Shreeshrii** [comment]
See https://github.com/tesseract-ocr/tesseract/issues/3156#issuecomment-731984098
