### ISSUE TITLE
tesser-ocr build failed with tesseract 5.0 

### ISSUE THREAD

**Issue by kbrajwani** [tesseract-ocr/tesseract#3245]
i am getting build failed error when i am installing tesserocr it was working perfect before a week. But now i am getting this error.
tesseract/genericvector.h: No such file or directory

i am using tesseract 5.0 you can see version detail as follows.

### Environment
tesseract 5.0.0-alpha-20201231-86-g95b9
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found OpenMP 201511
 Found libarchive 3.2.2 zlib/1.2.11 liblzma/5.2.2 bz2lib/1.0.6 liblz4/1.7.1
os : ubuntu 18.04

### current behaviour
Complete log of tesseocr installation

```
2021-01-18T11:58:51,968 Created temporary directory: /tmp/pip-ephem-wheel-cache-xcc6h8iq
2021-01-18T11:58:51,968 Created temporary directory: /tmp/pip-req-tracker-zvay71ys
2021-01-18T11:58:51,969 Created requirements tracker '/tmp/pip-req-tracker-zvay71ys'
2021-01-18T11:58:51,969 Created temporary directory: /tmp/pip-install-pnyj1i7m
2021-01-18T11:58:52,046 1 location(s) to search for versions of tesserocr:
2021-01-18T11:58:52,046 * https://pypi.org/simple/tesserocr/
2021-01-18T11:58:52,046 Getting page https://pypi.org/simple/tesserocr/
2021-01-18T11:58:52,047 Found index url https://pypi.org/simple
2021-01-18T11:58:52,128 Analyzing links from page https://pypi.org/simple/tesserocr/
2021-01-18T11:58:52,129   Found link https://files.pythonhosted.org/packages/c4/3f/ee98bf1bd27fda8d2d2a4685cb8c27045cbb06f7dc22afdb50f71969f109/tesserocr-1.2.1rc2.tar.gz#sha256=a11152100583492c697edee5ae239d66d856ff42aa253704455781412305b347 (from https://pypi.org/simple/tesserocr/), version: 1.2.1rc2
2021-01-18T11:58:52,129   Found link https://files.pythonhosted.org/packages/00/da/312caf79300fa0add6278a8ab8c133a70ac8912a287055a5fa37d13a42c9/tesserocr-2.0.0.tar.gz#sha256=8f0ef4058c51b0ba7de7d14b0357fd00eb970762b56fb5308016bcb5382af1da (from https://pypi.org/simple/tesserocr/), version: 2.0.0
2021-01-18T11:58:52,129   Found link https://files.pythonhosted.org/packages/6e/7b/1962b65567c1643f457f1255f862fdb50c99eb33aabd91c2d8e2c223ab16/tesserocr-2.1.1.tar.gz#sha256=f7edf01c67667d660c2423b085d50e7d84683b68e234b76f4a5e3a06a1a59c26 (from https://pypi.org/simple/tesserocr/), version: 2.1.1
2021-01-18T11:58:52,129   Found link https://files.pythonhosted.org/packages/48/9c/16ee28e2cd47dd3016eab35f131175baac5fdbf0e50ba7f7b07bac226f8f/tesserocr-2.1.2.tar.gz#sha256=93748442c9b3fc499ac5061b7e188b89c37212ad07f348064e4b3d079d80bd75 (from https://pypi.org/simple/tesserocr/), version: 2.1.2
2021-01-18T11:58:52,129   Found link https://files.pythonhosted.org/packages/ee/4b/a1627425460855f5aa83d072094349a2fe4550443faabcfdefccb212236c/tesserocr-2.1.3.tar.gz#sha256=3a75c702f6e787ea4f16f26a9909910b731bc388b415b3b54d42e766b4f481ae (from https://pypi.org/simple/tesserocr/), version: 2.1.3
2021-01-18T11:58:52,129   Found link https://files.pythonhosted.org/packages/dc/30/dd254d6e13ed097d4330bf4bec6d1f038af4deeec62488f65fb5b74ad15f/tesserocr-2.2.0.tar.gz#sha256=989fa2541c55370d3779fcb0b3646aa3b43045b4a72799b6ccc44f72517f99ce (from https://pypi.org/simple/tesserocr/), version: 2.2.0
2021-01-18T11:58:52,130   Found link https://files.pythonhosted.org/packages/c9/bc/f10f88a2d8a421ff565624a2759de16078980b9384da59198ebf4b0444ac/tesserocr-2.2.1.tar.gz#sha256=1805e9285246fec02e45ff76c7b0c13c4de388fa0d900d364c99e3928edf061c (from https://pypi.org/simple/tesserocr/), version: 2.2.1
2021-01-18T11:58:52,130   Found link https://files.pythonhosted.org/packages/cf/0d/9e554f041962b8dd7acd978330535fed879452bb0af257c287ca4ae9c525/tesserocr-2.2.2.tar.gz#sha256=f245c85643acaa6c740885c2cb18c6ca2ddb569756fbdeb10bd85a08c0a9fff2 (from https://pypi.org/simple/tesserocr/), version: 2.2.2
2021-01-18T11:58:52,130   Found link https://files.pythonhosted.org/packages/49/fc/f5d3ca8606566073919a5964118591734e91ee8e42adcc0cc8fcefc3953a/tesserocr-2.3.0.tar.gz#sha256=de1c57808f4a3ca59540750114537246685f447a11b0be1abb15b51680189719 (from https://pypi.org/simple/tesserocr/), version: 2.3.0
2021-01-18T11:58:52,130   Found link https://files.pythonhosted.org/packages/f8/6d/4e81e041f33a4419e59edcb1dbdf3c56e9393f60f5ef531381bd67a1339b/tesserocr-2.3.1.tar.gz#sha256=72ac9b6bd2c6b76c9c512494824d3d741bc314abbf2ae9b91d128ba81fdffd11 (from https://pypi.org/simple/tesserocr/), version: 2.3.1
2021-01-18T11:58:52,130   Found link https://files.pythonhosted.org/packages/92/2d/05a7f8387e93c192919b508e4f4936f232bd3d2ca388b9130ae538a9f9ad/tesserocr-2.4.0.tar.gz#sha256=ba60466fc91835656d4b4f93deb4ba7543d1588722ec4e0b84cc694500373b85 (from https://pypi.org/simple/tesserocr/), version: 2.4.0
2021-01-18T11:58:52,130   Found link https://files.pythonhosted.org/packages/97/14/2297039bd74baf2ce970549d4fec383fb6e435d0a48f79813f195834937f/tesserocr-2.4.1.tar.gz#sha256=8becfe0542a1a118fe92f9b2c1fc0ded9c90ce12a8374b3de33a9e20179fa546 (from https://pypi.org/simple/tesserocr/), version: 2.4.1
2021-01-18T11:58:52,130   Found link https://files.pythonhosted.org/packages/e3/77/fb26b321c3b9ce4a47af12b19e85ddbf4d0629adb6552d85276e824e6e51/tesserocr-2.5.0.tar.gz#sha256=3bca978dae9e03a327414d3da86954a943233a5169e25aaef14cddbb791d435a (from https://pypi.org/simple/tesserocr/), version: 2.5.0
2021-01-18T11:58:52,130   Found link https://files.pythonhosted.org/packages/9b/98/b4a534c4f3da4163c8c3d4dfdb1619748b7fe7d8c4fc4718cad3cda55e32/tesserocr-2.5.1.tar.gz#sha256=b0a6f44044217f962541f3166c817023cf149d208cd5cb19cc46fc1032698731 (from https://pypi.org/simple/tesserocr/), version: 2.5.1
2021-01-18T11:58:52,132 Given no hashes to check 13 links for project 'tesserocr': discarding no candidates
2021-01-18T11:58:52,132 Using version 2.5.1 (newest of versions: 2.0.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.5.1)
2021-01-18T11:58:52,134 Collecting tesserocr
2021-01-18T11:58:52,135   Created temporary directory: /tmp/pip-unpack-iy8h7l3o
2021-01-18T11:58:52,137   Using cached https://files.pythonhosted.org/packages/9b/98/b4a534c4f3da4163c8c3d4dfdb1619748b7fe7d8c4fc4718cad3cda55e32/tesserocr-2.5.1.tar.gz
2021-01-18T11:58:52,147   Added tesserocr from https://files.pythonhosted.org/packages/9b/98/b4a534c4f3da4163c8c3d4dfdb1619748b7fe7d8c4fc4718cad3cda55e32/tesserocr-2.5.1.tar.gz#sha256=b0a6f44044217f962541f3166c817023cf149d208cd5cb19cc46fc1032698731 to build tracker '/tmp/pip-req-tracker-zvay71ys'
2021-01-18T11:58:52,147     Running setup.py (path:/tmp/pip-install-pnyj1i7m/tesserocr/setup.py) egg_info for package tesserocr
2021-01-18T11:58:52,147     Running command python setup.py egg_info
2021-01-18T11:58:52,556     Supporting tesseract v5.0.0-alpha-20201231-86-g95b9
2021-01-18T11:58:52,556     Configs from pkg-config: {'library_dirs': [], 'include_dirs': ['/usr/include', '/usr/include'], 'libraries': ['tesseract', 'archive', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 1294778559894065}}
2021-01-18T11:58:52,615     running egg_info
2021-01-18T11:58:52,616     creating /tmp/pip-install-pnyj1i7m/tesserocr/pip-egg-info/tesserocr.egg-info
2021-01-18T11:58:52,617     writing /tmp/pip-install-pnyj1i7m/tesserocr/pip-egg-info/tesserocr.egg-info/PKG-INFO
2021-01-18T11:58:52,617     writing dependency_links to /tmp/pip-install-pnyj1i7m/tesserocr/pip-egg-info/tesserocr.egg-info/dependency_links.txt
2021-01-18T11:58:52,618     writing top-level names to /tmp/pip-install-pnyj1i7m/tesserocr/pip-egg-info/tesserocr.egg-info/top_level.txt
2021-01-18T11:58:52,618     writing manifest file '/tmp/pip-install-pnyj1i7m/tesserocr/pip-egg-info/tesserocr.egg-info/SOURCES.txt'
2021-01-18T11:58:53,803     Compiling tesserocr.pyx because it changed.
2021-01-18T11:58:53,804     [1/1] Cythonizing tesserocr.pyx
2021-01-18T11:58:53,815     reading manifest file '/tmp/pip-install-pnyj1i7m/tesserocr/pip-egg-info/tesserocr.egg-info/SOURCES.txt'
2021-01-18T11:58:53,816     reading manifest template 'MANIFEST.in'
2021-01-18T11:58:53,817     /usr/local/lib/python3.6/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-pnyj1i7m/tesserocr/tesserocr.pyx
2021-01-18T11:58:53,818       tree = Parsing.p_module(s, pxd, full_module_name)
2021-01-18T11:58:53,818     warning: no previously-included files found matching '*.so'
2021-01-18T11:58:53,819     writing manifest file '/tmp/pip-install-pnyj1i7m/tesserocr/pip-egg-info/tesserocr.egg-info/SOURCES.txt'
2021-01-18T11:58:54,015   Source in /tmp/pip-install-pnyj1i7m/tesserocr has version 2.5.1, which satisfies requirement tesserocr from https://files.pythonhosted.org/packages/9b/98/b4a534c4f3da4163c8c3d4dfdb1619748b7fe7d8c4fc4718cad3cda55e32/tesserocr-2.5.1.tar.gz#sha256=b0a6f44044217f962541f3166c817023cf149d208cd5cb19cc46fc1032698731
2021-01-18T11:58:54,015   Removed tesserocr from https://files.pythonhosted.org/packages/9b/98/b4a534c4f3da4163c8c3d4dfdb1619748b7fe7d8c4fc4718cad3cda55e32/tesserocr-2.5.1.tar.gz#sha256=b0a6f44044217f962541f3166c817023cf149d208cd5cb19cc46fc1032698731 from build tracker '/tmp/pip-req-tracker-zvay71ys'
2021-01-18T11:58:54,078 Building wheels for collected packages: tesserocr
2021-01-18T11:58:54,079   Created temporary directory: /tmp/pip-wheel-yglk0z0y
2021-01-18T11:58:54,079   Destination directory: /tmp/pip-wheel-yglk0z0y
2021-01-18T11:58:54,079   Running command /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pnyj1i7m/tesserocr/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pnyj1i7m/tesserocr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yglk0z0y --python-tag cp36
2021-01-18T11:58:54,496   Supporting tesseract v5.0.0-alpha-20201231-86-g95b9
2021-01-18T11:58:54,497   Configs from pkg-config: {'library_dirs': [], 'include_dirs': ['/usr/include', '/usr/include'], 'libraries': ['tesseract', 'archive', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 1294778559894065}}
2021-01-18T11:58:54,556   running bdist_wheel
2021-01-18T11:58:54,559   running build
2021-01-18T11:58:54,559   running build_ext
2021-01-18T11:58:54,725   building 'tesserocr' extension
2021-01-18T11:58:54,725   creating build
2021-01-18T11:58:54,725   creating build/temp.linux-x86_64-3.6
2021-01-18T11:58:54,725   x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include -I/usr/include/python3.6m -c tesserocr.cpp -o build/temp.linux-x86_64-3.6/tesserocr.o -std=c++11 -DUSE_STD_NAMESPACE
2021-01-18T11:58:54,815   tesserocr.cpp:680:10: fatal error: tesseract/genericvector.h: No such file or directory
2021-01-18T11:58:54,815    #include "tesseract/genericvector.h"
2021-01-18T11:58:54,815             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-01-18T11:58:54,815   compilation terminated.
2021-01-18T11:58:54,818   error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
2021-01-18T11:58:54,901   ERROR: Failed building wheel for tesserocr
2021-01-18T11:58:54,902   Running setup.py clean for tesserocr
2021-01-18T11:58:54,902   Running command /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pnyj1i7m/tesserocr/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pnyj1i7m/tesserocr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
2021-01-18T11:58:55,326   Supporting tesseract v5.0.0-alpha-20201231-86-g95b9
2021-01-18T11:58:55,327   Configs from pkg-config: {'library_dirs': [], 'include_dirs': ['/usr/include', '/usr/include'], 'libraries': ['tesseract', 'archive', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 1294778559894065}}
2021-01-18T11:58:55,376   running clean
2021-01-18T11:58:55,377   removing 'build/temp.linux-x86_64-3.6' (and everything under it)
2021-01-18T11:58:55,378   'build/lib.linux-x86_64-3.6' does not exist -- can't clean it
2021-01-18T11:58:55,378   'build/bdist.linux-x86_64' does not exist -- can't clean it
2021-01-18T11:58:55,378   'build/scripts-3.6' does not exist -- can't clean it
2021-01-18T11:58:55,378   removing 'build'
2021-01-18T11:58:55,421 Failed to build tesserocr
2021-01-18T11:58:57,252 Installing collected packages: tesserocr
2021-01-18T11:58:57,254   Created temporary directory: /tmp/pip-record-itxuxvmb
2021-01-18T11:58:57,254     Running command /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pnyj1i7m/tesserocr/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pnyj1i7m/tesserocr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-itxuxvmb/install-record.txt --single-version-externally-managed --compile
2021-01-18T11:58:57,697     Supporting tesseract v5.0.0-alpha-20201231-86-g95b9
2021-01-18T11:58:57,697     Configs from pkg-config: {'library_dirs': [], 'include_dirs': ['/usr/include', '/usr/include'], 'libraries': ['tesseract', 'archive', 'lept'], 'cython_compile_time_env': {'TESSERACT_VERSION': 1294778559894065}}
2021-01-18T11:58:57,746     running install
2021-01-18T11:58:57,748     running build
2021-01-18T11:58:57,748     running build_ext
2021-01-18T11:58:57,907     building 'tesserocr' extension
2021-01-18T11:58:57,907     creating build
2021-01-18T11:58:57,907     creating build/temp.linux-x86_64-3.6
2021-01-18T11:58:57,907     x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include -I/usr/include/python3.6m -c tesserocr.cpp -o build/temp.linux-x86_64-3.6/tesserocr.o -std=c++11 -DUSE_STD_NAMESPACE
2021-01-18T11:58:58,003     tesserocr.cpp:680:10: fatal error: tesseract/genericvector.h: No such file or directory
2021-01-18T11:58:58,003      #include "tesseract/genericvector.h"
2021-01-18T11:58:58,003               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-01-18T11:58:58,003     compilation terminated.
2021-01-18T11:58:58,007     error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
2021-01-18T11:58:58,075 Cleaning up...
2021-01-18T11:58:58,075   Removing source in /tmp/pip-install-pnyj1i7m/tesserocr
2021-01-18T11:58:58,078 Removed build tracker '/tmp/pip-req-tracker-zvay71ys'
2021-01-18T11:58:58,078 ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pnyj1i7m/tesserocr/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pnyj1i7m/tesserocr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-itxuxvmb/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
2021-01-18T11:58:58,079 Exception information:
2021-01-18T11:58:58,079 Traceback (most recent call last):
2021-01-18T11:58:58,079   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 153, in _main
2021-01-18T11:58:58,079     status = self.run(options, args)
2021-01-18T11:58:58,079   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 455, in run
2021-01-18T11:58:58,079     use_user_site=options.use_user_site,
2021-01-18T11:58:58,079   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 62, in install_given_reqs
2021-01-18T11:58:58,079     **kwargs
2021-01-18T11:58:58,079   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 888, in install
2021-01-18T11:58:58,079     cwd=self.unpacked_source_directory,
2021-01-18T11:58:58,079   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 275, in runner
2021-01-18T11:58:58,079     spinner=spinner,
2021-01-18T11:58:58,079   File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
2021-01-18T11:58:58,079     raise InstallationError(exc_msg)
2021-01-18T11:58:58,079 pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pnyj1i7m/tesserocr/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pnyj1i7m/tesserocr/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-itxuxvmb/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```

you can reproduce error as shown in colab
https://colab.research.google.com/drive/18DsNbTqpAJfKuyYZPiW9nd0CFOTtnbuZ?usp=sharing

**Comment by amitdo** [comment]
The 'master' branch is a development branch, so a breakage like this can happen.

**Comment by stweil** [comment]
The Tesseract API had a lot of changes recently, so `tesserocr` needs an update to work with those changes.

This is done by pull request https://github.com/sirfz/tesserocr/pull/242 which is still waiting to get merged by @sirfz.

**Comment by kbrajwani** [comment]
Thanks for the reply. can you tell me where can I know about features that are added in tesseract5?

**Comment by sirfz** [comment]
thanks for the ping @stweil, the PR has been merged

**Comment by srinivas1746** [comment]
Hi, @kbrajwani , can you please provide me the instructions to build tesser-ocr with tesseract 5.0. I was unable to find proper instructions.
