### ISSUE TITLE
Memory Leak with address sanitizers

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#3246]
Built with 
```
../../configure --enable-openmp --disable-shared --disable-debug  --disable-opencl --disable-legacy --disable-graphics --with-tensorflow=no 'CXXFLAGS=-g -O2 -Wall -Wextra -Wpedantic -fsanitize=address,undefined -fstack-protector-strong -ftrapv'
```

```
text2image -v
Using CAIRO_FONT_TYPE_FT.
Pango version: 1.40.14
5.0.0-alpha-20201231-147-g2c89

+ tesstrain.sh --fonts_dir /home/ubuntu/.fonts --fontlist Amiri --lang ara --linedata_only --noextract_font_properties --exposures 0 --langdata_dir /home/ubuntu/langdata_lstm --tessdata_dir /home/ubuntu/tessdata_best --save_box_tiff --maxpages 1 --output_dir /home/ubuntu/train

=== Starting training for language 'ara'
[Tue Jan 19 15:46:58 UTC 2021] /usr/local/bin/text2image --fonts_dir=/home/ubuntu/.fonts --ptsize 12 --font=Amiri --outputbase=/tmp/font_tmp.2LKT52Ayf0/sample_text.txt --text=/tmp/font_tmp.2LKT52Ayf0/sample_text.txt --fontconfig_tmpdir=/tmp/font_tmp.2LKT52Ayf0
Rendered page 0 to file /tmp/font_tmp.2LKT52Ayf0/sample_text.txt.tif

=================================================================
==30780==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 768 byte(s) in 1 object(s) allocated from:
    #0 0xffff8cbd9eeb in __interceptor_realloc (/usr/lib/aarch64-linux-gnu/libasan.so.4+0xcfeeb)
    #1 0xffff8c3496a3  (/usr/lib/aarch64-linux-gnu/libfontconfig.so.1+0x1e6a3)
    #2 0xffff8c349daf  (/usr/lib/aarch64-linux-gnu/libfontconfig.so.1+0x1edaf)
    #3 0xffff8c34680f in FcFontRenderPrepare (/usr/lib/aarch64-linux-gnu/libfontconfig.so.1+0x1b80f)
    #4 0xffff8c346cff in FcFontMatch (/usr/lib/aarch64-linux-gnu/libfontconfig.so.1+0x1bcff)
    #5 0xffff8c549cff  (/usr/lib/aarch64-linux-gnu/libpangoft2-1.0.so.0+0xacff)
    #6 0xffff8c549fb7  (/usr/lib/aarch64-linux-gnu/libpangoft2-1.0.so.0+0xafb7)
    #7 0xffff8c500cd7  (/usr/lib/aarch64-linux-gnu/libpango-1.0.so.0+0x18cd7)
    #8 0xffff8c50127b  (/usr/lib/aarch64-linux-gnu/libpango-1.0.so.0+0x1927b)
    #9 0xffff8c502537 in pango_itemize_with_base_dir (/usr/lib/aarch64-linux-gnu/libpango-1.0.so.0+0x1a537)
    #10 0xffff8c50b4f7  (/usr/lib/aarch64-linux-gnu/libpango-1.0.so.0+0x234f7)
    #11 0xffff8c50dd37  (/usr/lib/aarch64-linux-gnu/libpango-1.0.so.0+0x25d37)
    #12 0xffff8c50de63 in pango_layout_get_iter (/usr/lib/aarch64-linux-gnu/libpango-1.0.so.0+0x25e63)
    #13 0xaaaab38b1703 in tesseract::StringRenderer::FindFirstPageBreakOffset(char const*, int) ../../src/training/pango/stringrenderer.cpp:300
    #14 0xaaaab38c5487 in tesseract::StringRenderer::RenderToImage(char const*, int, Pix**) ../../src/training/pango/stringrenderer.cpp:741
    #15 0xaaaab38355e3 in Main ../../src/training/text2image.cpp:640
    #16 0xaaaab381657b in main ../../src/training/text2image.cpp:746
    #17 0xffff8b02271f in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x2071f)
    #18 0xaaaab382ba07  (/usr/local/bin/text2image+0x1a6ca07)

...


SUMMARY: AddressSanitizer: 19629 byte(s) leaked in 470 allocation(s).
ERROR: Program text2image failed. Abort.

```

**Comment by stweil** [comment]
[This line](https://github.com/tesseract-ocr/tesseract/blob/master/unittest/Makefile.am#L21) from `unittest/Makefile.am` should help to suppress leaks from libfontconfig.

**Comment by Shreeshrii** [comment]
@stweil Thanks.   I will set LSAN_OPTIONS in my shell profile.

Does it need to be added to Makefile.am in root?

Are you going to change unittests to flat build?

**Comment by stweil** [comment]
Yes, I'd like to change unittest to flat build, too. Then `LSAN_OPTIONS` would be set in the root `Makefile.am`.

I have an open question https://github.com/tesseract-ocr/tesseract/issues/3220#issuecomment-758235379 and would be interested in your opinion.

**Comment by Shreeshrii** [comment]
I have added `LSAN_OPTIONS=suppressions=/home/ubuntu/tesseract/unittest/tesseract_leaksanitizer.supp` to shell profile and it shows up in env. but still getting some errors while trying to run unlvtests.

```
Testing on set doe3.3B in directory /home/ubuntu/ISRI-OCRtk/doe3.3B to unlvtests/results/doe3.3B
0202_005.3B 24.85
Image too small to scale!! (1x36 vs min width of 3)
Line cannot be recognized!!
Image too small to scale!! (1x36 vs min width of 3)
0208_230.3B 33.14cognized!!
Image too small to scale!! (2x36 vs min width of 3)
0212_093.3B 19.99cognized!!

=================================================================
==21303==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0xffffa953843b in operator new(unsigned long) (/usr/lib/aarch64-linux-gnu/libasan.so.4+0xd243b)
    #1 0xaaaab078fa0f in tesseract::C_BLOB::ConstructBlobsFromOutlines(bool, tesseract::C_OUTLINE_LIST*, tesseract::C_BLOB_IT*, tesseract::C_BLOB_IT*) ../../src/ccstruct/stepblob.cpp:215
    #2 0xaaaab09ac5c3 in tesseract::empty_buckets(tesseract::BLOCK*, tesseract::OL_BUCKETS*) ../../src/textord/edgblob.cpp:422
    #3 0xaaaab09aeab3 in tesseract::outlines_to_blobs(tesseract::BLOCK*, tesseract::ICOORD, tesseract::ICOORD, tesseract::C_OUTLINE_LIST*) ../../src/textord/edgblob.cpp:361
    #4 0xaaaab09af087 in tesseract::extract_edges(Pix*, tesseract::BLOCK*) ../../src/textord/edgblob.cpp:342
    #5 0xaaaab0b2fb53 in tesseract::Textord::find_components(Pix*, tesseract::BLOCK_LIST*, tesseract::TO_BLOCK_LIST*) ../../src/textord/tordmain.cpp:235
    #6 0xaaaab0b1c163 in tesseract::Textord::TextordPage(tesseract::PageSegMode, tesseract::FCOORD const&, int, int, Pix*, Pix*, Pix*, bool, tesseract::BLOBNBOX_LIST*, tesseract::BLOCK_LIST*, tesseract::TO_BLOCK_LIST*) ../../src/textord/textord.cpp:235
    #7 0xaaaab04980fb in tesseract::Tesseract::SegmentPage(char const*, tesseract::BLOCK_LIST*, tesseract::Tesseract*, tesseract::OSResults*) ../../src/ccmain/pagesegmain.cpp:172
    #8 0xaaaab0361503 in tesseract::TessBaseAPI::FindLines() ../../src/api/baseapi.cpp:2085
    #9 0xaaaab0378d27 in tesseract::TessBaseAPI::Recognize(tesseract::ETEXT_DESC*) ../../src/api/baseapi.cpp:819
    #10 0xaaaab037d67f in tesseract::TessBaseAPI::ProcessPage(Pix*, int, char const*, char const*, int, tesseract::TessResultRenderer*) ../../src/api/baseapi.cpp:1231
    #11 0xaaaab03807c7 in tesseract::TessBaseAPI::ProcessPagesMultipageTiff(unsigned char const*, unsigned long, char const*, char const*, int, tesseract::TessResultRenderer*, int) ../../src/api/baseapi.cpp:1013
    #12 0xaaaab0382afb in tesseract::TessBaseAPI::ProcessPagesInternal(char const*, char const*, int, tesseract::TessResultRenderer*) ../../src/api/baseapi.cpp:1186
    #13 0xaaaab032bda7 in main ../../src/api/tesseractmain.cpp:785
    #14 0xffffa815d71f in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x2071f)
    #15 0xaaaab0341e3f  (/home/ubuntu/tesseract/bin/aarch/tesseract+0x17d7e3f)

Indirect leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0xffffa953843b in operator new(unsigned long) (/usr/lib/aarch64-linux-gnu/libasan.so.4+0xd243b)
    #1 0xaaaab0dfc3af in tesseract::complete_edge(tesseract::CRACKEDGE*, tesseract::C_OUTLINE_IT*) ../../src/textord/edgloop.cpp:51
    #2 0xaaaab09e30e3 in join_edges ../../src/textord/scanedg.cpp:375
    #3 0xaaaab09e3fdb in line_edges ../../src/textord/scanedg.cpp:201
    #4 0xaaaab09e3fdb in tesseract::block_edges(Pix*, tesseract::PDBLK*, tesseract::C_OUTLINE_IT*) ../../src/textord/scanedg.cpp:102
    #5 0xaaaab09aeebb in tesseract::extract_edges(Pix*, tesseract::BLOCK*) ../../src/textord/edgblob.cpp:337
    #6 0xaaaab0b2fb53 in tesseract::Textord::find_components(Pix*, tesseract::BLOCK_LIST*, tesseract::TO_BLOCK_LIST*) ../../src/textord/tordmain.cpp:235
    #7 0xaaaab0b1c163 in tesseract::Textord::TextordPage(tesseract::PageSegMode, tesseract::FCOORD const&, int, int, Pix*, Pix*, Pix*, bool, tesseract::BLOBNBOX_LIST*, tesseract::BLOCK_LIST*, tesseract::TO_BLOCK_LIST*) ../../src/textord/textord.cpp:235
    #8 0xaaaab04980fb in tesseract::Tesseract::SegmentPage(char const*, tesseract::BLOCK_LIST*, tesseract::Tesseract*, tesseract::OSResults*) ../../src/ccmain/pagesegmain.cpp:172
    #9 0xaaaab0361503 in tesseract::TessBaseAPI::FindLines() ../../src/api/baseapi.cpp:2085
    #10 0xaaaab0378d27 in tesseract::TessBaseAPI::Recognize(tesseract::ETEXT_DESC*) ../../src/api/baseapi.cpp:819
    #11 0xaaaab037d67f in tesseract::TessBaseAPI::ProcessPage(Pix*, int, char const*, char const*, int, tesseract::TessResultRenderer*) ../../src/api/baseapi.cpp:1231
    #12 0xaaaab03807c7 in tesseract::TessBaseAPI::ProcessPagesMultipageTiff(unsigned char const*, unsigned long, char const*, char const*, int, tesseract::TessResultRenderer*, int) ../../src/api/baseapi.cpp:1013
    #13 0xaaaab0382afb in tesseract::TessBaseAPI::ProcessPagesInternal(char const*, char const*, int, tesseract::TessResultRenderer*) ../../src/api/baseapi.cpp:1186
    #14 0xaaaab032bda7 in main ../../src/api/tesseractmain.cpp:785
    #15 0xffffa815d71f in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x2071f)
    #16 0xaaaab0341e3f  (/home/ubuntu/tesseract/bin/aarch/tesseract+0x17d7e3f)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0xffffa95385fb in operator new[](unsigned long) (/usr/lib/aarch64-linux-gnu/libasan.so.4+0xd25fb)
    #1 0xaaaab06445fb in tesseract::C_OUTLINE::ComputeBinaryOffsets() ../../src/ccstruct/coutln.cpp:847
    #2 0xaaaab07858d7 in ComputeEdgeOffsetsOutlineList ../../src/ccstruct/stepblob.cpp:410
    #3 0xaaaab05e5bef in tesseract::BLOBNBOX::ComputeEdgeOffsets(Pix*, Pix*, tesseract::BLOBNBOX_LIST*) ../../src/ccstruct/blobbox.cpp:413
    #4 0xaaaab0b1c3b3 in tesseract::Textord::TextordPage(tesseract::PageSegMode, tesseract::FCOORD const&, int, int, Pix*, Pix*, Pix*, bool, tesseract::BLOBNBOX_LIST*, tesseract::BLOCK_LIST*, tesseract::TO_BLOCK_LIST*) ../../src/textord/textord.cpp:242
    #5 0xaaaab04980fb in tesseract::Tesseract::SegmentPage(char const*, tesseract::BLOCK_LIST*, tesseract::Tesseract*, tesseract::OSResults*) ../../src/ccmain/pagesegmain.cpp:172
    #6 0xaaaab0361503 in tesseract::TessBaseAPI::FindLines() ../../src/api/baseapi.cpp:2085
    #7 0xaaaab0378d27 in tesseract::TessBaseAPI::Recognize(tesseract::ETEXT_DESC*) ../../src/api/baseapi.cpp:819
    #8 0xaaaab037d67f in tesseract::TessBaseAPI::ProcessPage(Pix*, int, char const*, char const*, int, tesseract::TessResultRenderer*) ../../src/api/baseapi.cpp:1231
    #9 0xaaaab03807c7 in tesseract::TessBaseAPI::ProcessPagesMultipageTiff(unsigned char const*, unsigned long, char const*, char const*, int, tesseract::TessResultRenderer*, int) ../../src/api/baseapi.cpp:1013
    #10 0xaaaab0382afb in tesseract::TessBaseAPI::ProcessPagesInternal(char const*, char const*, int, tesseract::TessResultRenderer*) ../../src/api/baseapi.cpp:1186
    #11 0xaaaab032bda7 in main ../../src/api/tesseractmain.cpp:785
    #12 0xffffa815d71f in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x2071f)
    #13 0xaaaab0341e3f  (/home/ubuntu/tesseract/bin/aarch/tesseract+0x17d7e3f)

Indirect leak of 2 byte(s) in 1 object(s) allocated from:
    #0 0xffffa9535cff in __interceptor_calloc (/usr/lib/aarch64-linux-gnu/libasan.so.4+0xcfcff)
    #1 0xaaaab062d20f in tesseract::C_OUTLINE::C_OUTLINE(tesseract::CRACKEDGE*, tesseract::ICOORD, tesseract::ICOORD, short) ../../src/ccstruct/coutln.cpp:72
    #2 0xaaaab0dfc40f in tesseract::complete_edge(tesseract::CRACKEDGE*, tesseract::C_OUTLINE_IT*) ../../src/textord/edgloop.cpp:51
    #3 0xaaaab09e30e3 in join_edges ../../src/textord/scanedg.cpp:375
    #4 0xaaaab09e3fdb in line_edges ../../src/textord/scanedg.cpp:201
    #5 0xaaaab09e3fdb in tesseract::block_edges(Pix*, tesseract::PDBLK*, tesseract::C_OUTLINE_IT*) ../../src/textord/scanedg.cpp:102
    #6 0xaaaab09aeebb in tesseract::extract_edges(Pix*, tesseract::BLOCK*) ../../src/textord/edgblob.cpp:337
    #7 0xaaaab0b2fb53 in tesseract::Textord::find_components(Pix*, tesseract::BLOCK_LIST*, tesseract::TO_BLOCK_LIST*) ../../src/textord/tordmain.cpp:235
    #8 0xaaaab0b1c163 in tesseract::Textord::TextordPage(tesseract::PageSegMode, tesseract::FCOORD const&, int, int, Pix*, Pix*, Pix*, bool, tesseract::BLOBNBOX_LIST*, tesseract::BLOCK_LIST*, tesseract::TO_BLOCK_LIST*) ../../src/textord/textord.cpp:235
    #9 0xaaaab04980fb in tesseract::Tesseract::SegmentPage(char const*, tesseract::BLOCK_LIST*, tesseract::Tesseract*, tesseract::OSResults*) ../../src/ccmain/pagesegmain.cpp:172
    #10 0xaaaab0361503 in tesseract::TessBaseAPI::FindLines() ../../src/api/baseapi.cpp:2085
    #11 0xaaaab0378d27 in tesseract::TessBaseAPI::Recognize(tesseract::ETEXT_DESC*) ../../src/api/baseapi.cpp:819
    #12 0xaaaab037d67f in tesseract::TessBaseAPI::ProcessPage(Pix*, int, char const*, char const*, int, tesseract::TessResultRenderer*) ../../src/api/baseapi.cpp:1231
    #13 0xaaaab03807c7 in tesseract::TessBaseAPI::ProcessPagesMultipageTiff(unsigned char const*, unsigned long, char const*, char const*, int, tesseract::TessResultRenderer*, int) ../../src/api/baseapi.cpp:1013
    #14 0xaaaab0382afb in tesseract::TessBaseAPI::ProcessPagesInternal(char const*, char const*, int, tesseract::TessResultRenderer*) ../../src/api/baseapi.cpp:1186
    #15 0xaaaab032bda7 in main ../../src/api/tesseractmain.cpp:785
    #16 0xffffa815d71f in __libc_start_main (/lib/aarch64-linux-gnu/libc.so.6+0x2071f)
    #17 0xaaaab0341e3f  (/home/ubuntu/tesseract/bin/aarch/tesseract+0x17d7e3f)

121289_014.3B Command terminated by signal 2tus 1 allocation(s).
Counting on set doe3.3B in directory /home/ubuntu/ISRI-OCRtk/doe3.3B to unlvtests/results/doe3.3B
```

**Comment by stweil** [comment]
That looks like issue #2486 which was detected by fuzzing. I already spent a lot of time trying to fix that, but still have no solution. Modernizing the related code is difficult.

**Comment by Shreeshrii** [comment]
Closing as duplicate.
