### ISSUE TITLE
ELIST crashes during training

### ISSUE THREAD

**Issue by eighttails** [tesseract-ocr/tesseract#3405]
### Environment

* **Tesseract Version**: master
* **Commit Number**: e3ac1835e09de52b26eb5d56db65baf7e7d02edf
* **Platform**: Ubuntu 20.04 64bit

### Current Behavior:
Tesseract crashes in '=== Phase E: Generating lstmf files ===' phase certain generated image is input.
Here is gdb output.
It seems to refer deleted object.

```
tadahito@d048f01447f6:~/work/training$ gdb --arg /home/tadahito/local/bin/tesseract /tmp/jpn-2021-04-25q89xe2zz/jpn.Noto_Serif_CJK_JP_SemiBold.exp4.spc0.tif /tmp/jpn-2021-04-25q89xe2zz/jpn.Noto_Serif_CJK_JP_SemiBold.exp4.spc0 lstm.train /home/tadahito/work/training/langdata/jpn/jpn.config

GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/tadahito/local/bin/tesseract...
(gdb) r
Starting program: /home/tadahito/local/bin/tesseract /tmp/jpn-2021-04-25q89xe2zz/jpn.Noto_Serif_CJK_JP_SemiBold.exp4.spc0.tif /tmp/jpn-2021-04-25q89xe2zz/jpn.Noto_Serif_CJK_JP_SemiBold.exp4.spc0 lstm.train /home/tadahito/work/training/langdata/jpn/jpn.config
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Warning: Parameter not found: tessedit_single_match
Warning: Parameter not found: il1_adaption_test
Warning: Parameter not found: tessedit_single_match
Warning: Parameter not found: il1_adaption_test
Tesseract Open Source OCR Engine v5.0.0-alpha-20210401 with Leptonica
Page 1
Detected 10 diacritics

Program received signal SIGSEGV, Segmentation fault.
0x00007fcdf2b2e6f3 in tesseract::ELIST::internal_clear (this=this@entry=0x559859a3ebc8, zapper=zapper@entry=0x7fcdf298b710 <tesseract::X_LIST<tesseract::ELIST, tesseract::ELIST_ITERATOR, tesseract::C_OUTLINE>::clear()::{lambda(void*)#1}::_FUN(void*)>)
    at src/ccutil/elst.cpp:47
47            next = ptr->next;
(gdb) bt
#0  0x00007fcdf2b2e6f3 in tesseract::ELIST::internal_clear (this=this@entry=0x559859a3ebc8,
    zapper=zapper@entry=0x7fcdf298b710 <tesseract::X_LIST<tesseract::ELIST, tesseract::ELIST_ITERATOR, tesseract::C_OUTLINE>::clear()::{lambda(void*)#1}::_FUN(void*)>) at src/ccutil/elst.cpp:47
#1  0x00007fcdf29b899a in tesseract::X_LIST<tesseract::ELIST, tesseract::ELIST_ITERATOR, tesseract::C_OUTLINE>::clear (this=0x559859a3ebc8) at ./src/ccutil/list.h:53
#2  tesseract::X_LIST<tesseract::ELIST, tesseract::ELIST_ITERATOR, tesseract::C_OUTLINE>::~X_LIST (this=0x559859a3ebc8, __in_chrg=<optimized out>) at ./src/ccutil/list.h:49
#3  tesseract::C_OUTLINE_LIST::~C_OUTLINE_LIST (this=0x559859a3ebc8, __in_chrg=<optimized out>) at ./src/ccstruct/coutln.h:74
#4  tesseract::C_BLOB::~C_BLOB (this=0x559859a3ebc0, __in_chrg=<optimized out>) at ./src/ccstruct/stepblob.h:40
#5  tesseract::BLOBNBOX::~BLOBNBOX (this=<optimized out>, __in_chrg=<optimized out>) at ./src/ccstruct/blobbox.h:154
#6  tesseract::BLOBNBOX::~BLOBNBOX (this=<optimized out>, __in_chrg=<optimized out>) at ./src/ccstruct/blobbox.h:152
#7  0x00007fcdf2a8ce89 in tesseract::RotateAndExplodeBlobList (blob_rotation=..., bblobs=<optimized out>, widths=0x7ffe687b3f30, heights=0x7ffe687b3f50) at src/textord/colfind.cpp:1531
#8  0x00007fcdf2a8f211 in tesseract::ColumnFinder::RotateAndReskewBlocks (this=0x559859a2b150, input_is_rtl=false, blocks=<optimized out>) at src/textord/colfind.cpp:1583
#9  0x00007fcdf2a92868 in tesseract::ColumnFinder::FindBlocks (this=this@entry=0x559859a2b150, pageseg_mode=pageseg_mode@entry=tesseract::PSM_AUTO, scaled_color=..., scaled_factor=<optimized out>, input_block=input_block@entry=0x559859a3f1e0,
    photo_mask_pix=..., thresholds_pix=..., grey_pix=..., pixa_debug=0x7fcdef7d4bd0, blocks=0x7ffe687b4248, diacritic_blobs=0x7ffe687b42e8, to_blocks=0x7ffe687b42f0) at src/textord/colfind.cpp:471
#10 0x00007fcdf29b80df in tesseract::Tesseract::AutoPageSeg (this=0x7fcdef7b1010, pageseg_mode=tesseract::PSM_AUTO, blocks=0x559859a2b020, to_blocks=0x7ffe687b42f0, diacritic_blobs=0x7ffe687b42e8, osd_tess=<optimized out>, osr=0x7ffe687b46a0)
    at src/ccmain/pagesegmain.cpp:226
#11 0x00007fcdf29b859d in tesseract::Tesseract::SegmentPage (this=0x7fcdef7b1010, input_file=<optimized out>, blocks=0x559859a2b020, osd_tess=osd_tess@entry=0x0, osr=osr@entry=0x7ffe687b46a0) at ./src/ccutil/params.h:202
#12 0x00007fcdf29842e7 in tesseract::TessBaseAPI::FindLines (this=0x7ffe687b54a0) at /usr/include/c++/9/bits/basic_string.h:2300
#13 0x00007fcdf2986b08 in tesseract::TessBaseAPI::Recognize (this=0x7ffe687b54a0, monitor=0x0) at src/api/baseapi.cpp:836
#14 0x00007fcdf29870e2 in tesseract::TessBaseAPI::ProcessPage (this=this@entry=0x7ffe687b54a0, pix=0x559859a2b100, page_index=page_index@entry=0,
    filename=filename@entry=0x7ffe687b6669 "/tmp/jpn-2021-04-25q89xe2zz/jpn.Noto_Serif_CJK_JP_SemiBold.exp4.spc0.tif", retry_config=retry_config@entry=0x0, timeout_millisec=timeout_millisec@entry=0, renderer=0x0) at src/api/baseapi.cpp:1253
#15 0x00007fcdf298795e in tesseract::TessBaseAPI::ProcessPagesMultipageTiff (this=0x7ffe687b54a0, data=0x0, size=0, filename=0x7ffe687b6669 "/tmp/jpn-2021-04-25q89xe2zz/jpn.Noto_Serif_CJK_JP_SemiBold.exp4.spc0.tif", retry_config=0x0,
    timeout_millisec=0, renderer=<optimized out>, tessedit_page_number=-1) at src/api/baseapi.cpp:1050
#16 0x00007fcdf2988125 in tesseract::TessBaseAPI::ProcessPagesInternal (this=0x7ffe687b54a0, filename=<optimized out>, retry_config=0x0, timeout_millisec=0, renderer=0x0) at ./src/ccutil/params.h:160
#17 0x00007fcdf2988243 in tesseract::TessBaseAPI::ProcessPages (this=0x7ffe687b54a0, filename=<optimized out>, retry_config=<optimized out>, timeout_millisec=<optimized out>, renderer=<optimized out>) at src/api/baseapi.cpp:1069
#18 0x000055985775f680 in main (argc=<optimized out>, argv=<optimized out>) at /usr/include/c++/9/bits/unique_ptr.h:360
(gdb) p ptr
$1 = (tesseract::ELIST_LINK *) 0x2000000070002
(gdb) p ptr->next
Cannot access memory at address 0x2000000070002
(gdb)

```
Image file to reproduce the issue is here.
[tess_tmp.zip](https://github.com/tesseract-ocr/tesseract/files/6371216/tess_tmp.zip)

### Expected Behavior:
Training goes on without crash.

**Comment by egorpugin** [comment]
Ownership model is very c-style at the moment.
It will be upgraded eventually.
