### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tess_ghr25lln.txt'

### ISSUE THREAD

**Issue by Pranaysaha2** [tesseract-ocr/tesseract#3518]
Below issue is am facing when trying to hit api:

Traceback (most recent call last):
  File "/home/ec2-user/pythonApi/venv/lib64/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/pythonApi/venv/lib64/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/pythonApi/venv/lib64/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/pythonApi/venv/lib64/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ec2-user/pyApiWithFile.py", line 66, in processImage
    text = pytesseract.image_to_string("/home/ec2-user/tmp/pan.png")
  File "/home/ec2-user/pythonApi/venv/lib64/python3.6/site-packages/pytesseract/pytesseract.py", line 417, in image_to_string
    }[output_type]()
  File "/home/ec2-user/pythonApi/venv/lib64/python3.6/site-packages/pytesseract/pytesseract.py", line 416, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "/home/ec2-user/pythonApi/venv/lib64/python3.6/site-packages/pytesseract/pytesseract.py", line 286, in run_and_get_output
    with open(filename, 'rb') as output_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tess_ghr25lln.txt'

I checked and identify that file "/tmp/tess_ghr25lln.txt" is generating on this location "/tmp/snap.tesseract/tmp/tess_ghr25lln.txt".
Is there any way to change the tesseract output location?

**Comment by zdenop** [comment]
Please respect guidelines for posting issue: we do not provide support for 3rd party projects.
Reproduce your problem with resent version of **tesseract executable** and provide input image for reproducing error.
