### ISSUE TITLE
potential segementation falut by wrong format string

### ISSUE THREAD

**Issue by afosscontact** [tesseract-ocr/tesseract#3586]
### Environment

* **Tesseract Version**: 4.1
* **Commit Number**: 
* **Platform**: Ubuntu 18.04

### Current Behavior:
A bug was found within the tesseract. Though it might not be an intended use of the relevant API, the bug can still produce critical issues within a program using tesseract. It would be best if the affected logic is checked beforehand.
The bug was found with a fuzzer based on the test-code"Primes"

crash log
```
=================================================================
==35186==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000004c841e bp 0x7ffdcafe9470 sp 0x7ffdcafe9200 T0)
==35186==The signal is caused by a WRITE memory access.
==35186==Hint: address points to the zero page.
    #0 0x4c841e in tvfscanf(_IO_FILE*, char const*, __va_list_tag*) /root/fuzz-test-generation/exp/tesseract/src/ccutil/scanutils.cpp:383:44
    #1 0x4c841e in tfscanf(_IO_FILE*, char const*, ...) /root/fuzz-test-generation/exp/tesseract/src/ccutil/scanutils.cpp:194:8
    #2 0x4c5fbc in main /root/fuzz-test-generation/exp/tesseract/case6.cc:8:12
    #3 0x7fd3f12e4bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
    #4 0x41b7d9 in _start (/ssd_array/utopia_paper/fuzz-test-generation/exp/tesseract/case6+0x41b7d9)
```

Steps to reproduce:

  1. git clone https://github.com/tesseract-ocr/tesseract.git

  2. cd tesseract & ./autogen.sh & ./configure --prefix=$(pwd)/local --enable-shared=no CC="clang" CXX="clang++" CFLAGS="-g" CXXFLAGS="-g" LDFLAGS="-g"
  3. make
  4. Download the attached file and unzip(attach.zip)
  5. Build TEST CODE (case6.cc)
     clang++ -I./include -I./include -I./src/arch -I./src/ccmain -I./src/ccstruct -I./src/ccutil -I./src/cutil -I./src/dict -I./src/training/unicharset -I./src/viewer -fopenmp -g -std=c++17 -c -o case6.o case6.cc
   clang++ -fsanitize=address -fopenmp -g -std=c++17 -g -o case6 case6.o ./.libs/libtesseract.a -llept -lpthread -fopenmp
 6. Run
 ./case6

[attach.zip](https://github.com/tesseract-ocr/tesseract/files/7265180/attach.zip)

### Suggested Fix:
tvscanf function seems to be implemented to read files similar to scanf.
There is no exception handling when the number of va_arg is less than the number of format strings. The scanf function handles an exception in this case and segv does not occur.
So  it is necessary to make sure that handling exception.

**Comment by Shreeshrii** [comment]
You mention tesseract version as 4.1 but your instructions show you using got clone of the repo.

Are you using the source as per 4.1 tag or the latest version in git?

Please report the output of 'tesseract -v'

**Comment by afosscontact** [comment]
I used latest version in git. Branch is main branch

**Comment by stweil** [comment]
> The scanf function handles an exception in this case and segv does not occur.

Are you sure? I modified the test case to use `fscanf`, and that causes a segmentation fault, too. The only difference is that the compiler warns:

    case6.cc:6:32: warning: more '%' conversions than data arguments [-Wformat-insufficient-args]

So the required fix for Tesseract is adding the necessary `pragma` to the declaration of function `tfscanf`.

**Comment by stweil** [comment]
Does this issue still exist?
