### ISSUE TITLE
NoClassDefFoundError: Could not initialize class net.sourceforge.tess4j.TessAPI

### ISSUE THREAD

**Issue by zhouhz87** [tesseract-ocr/tesseract#3602]
Exception in thread "pool-2-thread-20828" java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.tess4j.TessAPI
	at net.sourceforge.tess4j.Tesseract.init(Tesseract.java:427)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:311)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:294)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:275)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:259)

tess4j version:4.5.5
window server 2008r2

**Comment by zdenop** [comment]
Please respect guidelines for posting issues: we do not provide support for 3rd party projects. Reproduce your problem with recent version of the tesseract executable and provide an input image for reproducing the error.
