### ISSUE TITLE
PSM: 2 Error Automatic page segmentation, but no OSD, or OCR.

### ISSUE THREAD

**Issue by anantgupta129** [tesseract-ocr/tesseract#3755]
Error when using Automatic page segmentation, but no OSD, or OCR.

```
Traceback (most recent call last):
  File "src/recognizers/tesseract/subservices/tesseract_image_to_string_request_handler.py", line 21, in process_request
  File "src/recognizers/tesseract/tesseract_recognizer.py", line 26, in recognize
  File "pytesseract/pytesseract.py", line 350, in image_to_string
  File "pytesseract/pytesseract.py", line 349, in <lambda>
  File "pytesseract/pytesseract.py", line 262, in run_and_get_output
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tess_i8onia3l.txt
```

This is the code:

```python
import cv2
import pytesseract

config = {
    "oem": 3,
    "psm": 2,
    "lang": "eng",
    "tessedit_char_whitelist": "",
    "preserve_interword_spaces": False,
    "output-preserve-enabled": False,
    "additional_tesseract_config": ""
}

image = cv2.imread(r"C:\Users\USER\Downloads\ocr test\e18ecd775147ef45bedb5a1b95470a5a.jpg")

tesseract_config = f"""--psm {config['psm']} --oem {config['oem']} -c tessedit_char_whitelist={config['tessedit_char_whitelist']} preserve_interword_spaces={int(config["preserve_interword_spaces"])}"""
if config["output-preserve-enabled"]:
    tesseract_config = " ".join([tesseract_config, "output-preserve-enabled"])

tesseract_config = ' '.join(filter(None, [tesseract_config, config["additional_tesseract_config"]]))
pred_text = pytesseract.image_to_string(image, lang=config['lang'], config=tesseract_config)

print(pred_text)

```

is this the correct way to use PSM 2?

**Comment by zdenop** [comment]
Please respect guidelines for posting issues: we do not provide support for 3rd party projects. Reproduce problem with recent version of the tesseract executable and provide an input image for reproducing the error.
