### ISSUE TITLE
LSTM: Deserialize header failed - Segmentation Fault

### ISSUE THREAD

**Issue by Shreeshrii** [tesseract-ocr/tesseract#691]
```
lstmtraining -U  /mnt/c/Users/User/shree/jtess/samples/vie/vie.unicharset  
 --script_dir /mnt/c/Usrs/User/shree/langdata  --debug_interval -1 
  --continue_from  /mnt/c/Users/User/shree/jtess/samples/vie/vie.lstm  
 --append_index 5 --net_spec '[Lfx256 O1c105]'   
--model_output  /mnt/c/Users/User/shree/jtess/samples/vie/vielayer  
 --train_listfile  /mnt/c/Users/User/shree/jtess/samples/vie/vie.training_files.txt  
 --target_error_rate 0.01

  Loaded file /mnt/c/Users/User/shree/jtess/samples/vie/vie.lstm, unpacking...
Warning: LSTMTrainer deserialized an LSTMRecognizer!
Continuing from /mnt/c/Users/User/shree/jtess/samples/vie/vie.lstm
Appending a new network to an old one!!Setting unichar properties
Setting properties for script Common
Setting properties for script Latin
Warning: given outputs 105 not equal to unicharset of 227.
Num outputs,weights in serial:
  Lfx256:256, 394240
  Fc227:227, 58339
Total weights = 452579
Built network:[1,0,0,1[C5,5Ft16]Mp3,3Lfys64Lfx128Lrx128Lfx256Fc227] from request [Lfx256 O1c105]
Training parameters:
  Debug interval = -1, weights = 0.1, learning rate = 0.0001, momentum=0.9
Deserialize header failed: /mnt/c/Users/User/shree/jtess/samples/vie/vie.FreeSerif.exp0.lstmf
Load of page 0 failed!
Load of images failed!!
```

**Comment by Shreeshrii** [comment]
note: lstmf files created using windows binaries

**Comment by Shreeshrii** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract-4.00#error-messages-from-training

>Deserialize header failed occurs when a training input is not in LSTM format or the file is not readable. Check your filelist file to see if it contains valid filenames.

**Comment by Shreeshrii** [comment]
The latest version of the code does not read lstmf files created prior to Ray's recent commits.

```
Deserialize header failed: ~/tesstutorial/tess4training-vedic/san.Akshar_Unicode.exp-2.lstmf
[Thread 0x7ffff2bb3700 (LWP 8327) exited]
[New Thread 0x7fffef194700 (LWP 8328)]
Deserialize header failed: ~/tesstutorial/tess4training-vedic/san.Aksharyogini2.exp0.lstmf
[New Thread 0x7ffff2bb3700 (LWP 8329)]
Load of page 0 failed!
Load of images failed!!
[Thread 0x7fffef194700 (LWP 8328) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff2bb3700 (LWP 8329)]
0x00007ffff70be464 in truncate (size=0, this=0x30790e8) at ../ccutil/genericvector.h:497
497           delete GenericVector<T*>::data_[i];
(gdb) backtrace
#0  0x00007ffff70be464 in truncate (size=0, this=0x30790e8) at ../ccutil/genericvector.h:497
#1  tesseract::DocumentData::ReCachePages (this=0x30790e0) at imagedata.cpp:523
#2  0x00007ffff70be839 in tesseract::ReCachePagesFunc (data=<optimized out>) at imagedata.cpp:371
#3  0x00007ffff419d184 in start_thread (arg=0x7ffff2bb3700) at pthread_create.c:312
#4  0x00007ffff6390ffd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by amitdo** [comment]
It's a moving target. and it's not guaranteed to read files generated by a previous alpha snapshot.

**Comment by Shreeshrii** [comment]
Ok. Closing the issue.
